# List of languages supported by Codewars, updated Nov 2020
#
# Extensions sourced from Github Linguist
# https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

file_extensions = {
    'agda': '.agda',
    'bf': '.bf',
    'c': '.c',
    'cfml': '.cfm',
    'clojure': '.clj',
    'cobol': '.cob',
    'coffeescript': '.coffee',
    'commonlisp': '.cl',
    'coq': '.v',
    'cpp': '.cpp',
    'crystal': '.cr',
    'csharp': '.cs',
    'dart': '.dart',
    'elixir': '.ex',
    'elm': '.elm',
    'erlang': '.erl',
    'factor': '.factor',
    'forth': '.fth',
    'fortran': '.f',
    'fsharp': '.fs',
    'go': '.go',
    'groovy': '.groovy',
    'haskell': '.hs',
    'haxe': '.hx',
    'idris': '.idr',
    'java': '.java',
    'javascript': '.js',
    'julia': '.jl',
    'kotlin': '.kt',
    'lean': '.lean',
    'lua': '.lua',
    'nasm': '.nasm',
    'nim': '.nim',
    'objc': '.m',
    'ocaml': '.ml',
    'perl': '.pl',
    'php': '.php',
    'powershell': '.ps1',
    'prolog': '.pro',
    'purescript': '.purs',
    'python': '.py',
    'r': '.r',
    'racket': '.rkt',
    'raku': '.p6',
    'reason': '.re',
    'ruby': '.rb',
    'rust': '.rs',
    'scala': '.scala',
    'shell': '.sh',
    'solidity': '.sol',
    'sql': '.sql',
    'swift': '.swift',
    'typescript': '.ts',
    'vb': '.vb'
}
